[package]
name = "day08_haunted_wasteland_part2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
day08_haunted_wasteland_common = { path = "../day08_haunted_wasteland_common" }
